### ISSUE TITLE
Question about the algorithm on CUTEst

### ISSUE THREAD

**Issue by Xiaoyi-Qu** [aldma/Bazinga.jl#3]
Hi Alberto, I am currently working on constrained composite optimization, primarily on ones with equality constraints. I am interested in comparing the performance between your method and our method based on problems from CUTEst. The reason for using CUTEst is that few applications can be found for ones with equality constraints only. For the testing purpose, I transformed the original test problem `min f(x) s.t. c(x) = 0` into `min f(x) + \|y\|_1 s.t. c(x) + y = 0`. In this way, the nonsmooth term is introduced.

Out of curiosity, I am wondering your expectation of the algorithm performance on CUTEst test problem variants. I attempted to add one file to the demo folder and to run the CUTEst test without further changes. It turns out that thousands of inner iterations are needed for each outer iteration and the last column(corresponding to tau) is zero. Both observations do not make sense to me. I am new to Julia and there is a great chance that I did something wrong in the code.

p.s. you can find the output attached. Thank you very much for any help and guidance.

![output](https://github.com/aldma/Bazinga.jl/assets/59779214/4b4b41b0-e3ad-4b5d-a6b6-898c4a0b3b39)

**Comment by aldma** [comment]
Hi @Xiaoyi-Qu , thanks for reaching out. I am glad you decided to give Bazinga.jl a try.
Based on what you said, I can hardly diagnose the problem, but I may have some pointers.
- How did you implement the reformulation from CUTEstModel to Bazinga's input? Is it tested? The stepsize `tau = 0` could indicate wrong gradient computations.
- Does it happen for all (or many) problems?
- I presume you are using PANOCplus as subsolver. This (disappointing) behaviour is quite odd indeed. You could try other solvers from ProximalAlgorithms.jl (such as ForwardBackward), allowing more sub-iterations. Using simpler methods may make it easier to spot errors or confine the issues.

Please feel free to post a MWE to reproduce this behaviour. I'd be happy to help.

**Comment by Xiaoyi-Qu** [comment]
Hi @aldma , thank you very much for your quick response!  I made two changes to my demo function and now it works for problem `HS7` from CUTEst. Details of this problem can be found on Page30 at the following [Link](https://www.yumpu.com/en/document/read/9631522/test-examples-for-nonlinear-programming-codes-klaus-schittkowski/3). The two changes are as follows.

- Use `als.jl` instead of `alps.jl`. 
- Modify the `Bazinga.prox!` function. I follow the same format given in the `rosenbrock.jl`.

After the above changes, the new output is presented as follows, which is super close to the optimal solution ([ $0$, $\sqrt{3}$, $0$ ]).

![output](https://github.com/aldma/Bazinga.jl/assets/59779214/2b470bc9-02bc-4011-a34b-9ac4958fd43c)

Based on the above changes, I am curious about
- What is the difference between `als.jl` and `alps.jl`?
- What's the functionality of the `Bazinga.prox!` function? 

For the second bullet point, if I understand correctly, `Bazinga.prox!` function serves to compute the nonsmooth cost function and meanwhile modify the iterate `x` if some element of the array `x` is close to zero. Thank you very much for any help! I will continue testing on other CUTEst problems and keep you updated if there are some interesting findings.

**Comment by aldma** [comment]
Hi @Xiaoyi-Qu , I am glad it is working now.

- `als.jl` is the solver developed in [this paper](https://doi.org/10.1007/s10107-022-01922-4) for problems in the format described in the README, that is, with explicit constraints. `alps.jl` is from [this paper](https://doi.org/10.48550/arXiv.2302.00363), still under review, which deals with problems in the form `minimize F(x) + G(C(x))` over `x ∈ Rⁿ`. The solver `alps.jl` uses a reformulation to match that format. For the moment it is safer, although perhaps less efficient, to use `als.jl`.
- The `Bazinga.prox!` function implements the proximal mapping of `g`. Given a point `x` and a stepsize `gamma`, `prox!(x, gamma)` overwrites `x` and returns the function value of `g` at the new point `x`. For the l1-norm in your problem, this is the soft-thresholding operator. For more examples you can have a look at [ProximalOperators.jl](https://github.com/JuliaFirstOrder/ProximalOperators.jl) or [proximity-operator](http://proximity-operator.net/).

**Comment by Xiaoyi-Qu** [comment]
Thank you very much for your detailed explanation!
